repos:
- repo: local
  hooks:
    - id: lint 
      name: Lint files 
      entry: uv
      language: system
      args: [run, invoke, lint]
      pass_filenames: false
    - id: format
      name: Format files
      entry: uv
      language: system
      args: [run, invoke, format]
      pass_filenames: false
