import click

from stega_cli.config import create_config
from stega_cli.cli.entrypoint import stega
from stega_cli.cli.utils import echo_banner
from stega_cli.daemon import acquire_connection, send_command, read_command
from stega_cli.domain.command import GetPortfolio, ListPortfolios, CreatePortfolio
from stega_lib import http


@stega.group()
def portfolio() -> None:
    """Commands for managing portfolios."""


@click.argument("portfolio_id")
@portfolio.command()
def get(portfolio_id: str) -> None:
    """Command to get a portfolio."""
    config = create_config()
    cmd = GetPortfolio(portfolio_id)
    with acquire_connection(config.sock_path) as conn:
        send_command(conn, cmd.to_dict())
        response = read_command(conn)
    
    result = response["result"]
    click.echo(result)


@portfolio.command()
def list() -> None:
    """Command to list existing portfolios."""
    config = create_config()
    cmd = ListPortfolios()

    with http.acquire_session(config.core_service_url) as session:
        resp = session.get("portfolios")
        resp.raise_for_status()
        data = resp.json()["result"]
    
    echo_banner("PORTFOLIOS")
    click.echo()
    for idx, portfolio in enumerate(data):
        name = portfolio["name"]
        assets = portfolio["assets"]
        echo_banner(f"Portfolio #{idx+1}", char="-")
        click.echo(f"Name: {name}")
        click.echo("Assets:")
        for asset in assets:
            symbol = asset["symbol"]
            weight = asset["weight"]
            click.echo(f"  - {symbol} ({weight:.2f})")
        click.echo()


@click.argument("name")
@click.option(
    "-f",
    "--portfolio-file",
    help="A csv of assets and weights to create a portfolio from.",
)
@portfolio.command()
def create(
    name: str,
    portfolio_file: str,
) -> None:
    """Command to create a new portfolio."""
    click.echo(f"Creating portfolio '{name}' from {portfolio_file}...")
    config = create_config()
    payload = _get_portfolio_payload(name, portfolio_file)

    # TODO: generate actual uuid for correlation ids, also this should be moved to generated by dispatch handler
    #
    # CommandRequest -> Daemon -> Dispatcher -> Generate Command -> Submit Command (Sync for reads, Async for writes on queue) -> Return Response -> Daemon -> CLI Response
    #
    # 
    # # Daemon
    # payload = await read_command_async(reader)
    # cmd_req = CommandRequest.from_dict(payload)
    # resp = dispatcher.handle(cmd_req)
    # await send_command_async(writer, resp.to_dict())
    #
    # # RequestDispatcher - for delegating read vs. write command requests
    # if isinstance(cmd_req, ReadCommandRequest):
    #       cmd = gen_read_cmd(cmd_req)
    #       return dispatcher.handle(cmd) # command dispatcher
    # elif isinstance(cmd_req, WriteCommandRequest):
    #       cmd = gen_write_cmd(cmd_req)
    #       await cmd_queue.put(cmd)
    #       return Response(..., cmd.correlation_id)
    #
    # # CommandDispatcher - for delegating actual command work
    #   - called synchronously in RequestDispatcher
    #   - called asynchronously in daemon handle_command for writes

    cmd = CreatePortfolio(
        correlation_id=str("test-id"),
        name=payload["name"],
        assets=payload["assets"],
    )

    with acquire_connection(config.sock_path) as conn:
        send_command(conn, cmd.to_dict())
        response = read_command(conn)

    result = response["result"]
    correlation_id = result["correlation_id"]
    click.echo(f"Successfully submitted request to create portfolio. Query latest result with id - {correlation_id}")


def _get_portfolio_payload(name: str, portfolio_file: str) -> dict[str, str | dict[str, float]]:
    payload = {"name": name, "assets": {} }
    with open(portfolio_file, "r", encoding="utf-8") as fd:
        for line in fd.readlines():
            symbol, weight = line.split(",")
            symbol = symbol.strip()
            weight = float(weight.strip())
            payload["assets"][symbol] = weight
    return payload

