services:
  edge:
    image: stega-edge:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      broker:
        condition: service_healthy
      portfolio:
        condition: service_healthy 
    environment:
      STEGA_EDGE_ENV: ${STEGA_EDGE_ENV}
      STEGA_EDGE_LOG_LEVEL: ${STEGA_EDGE_LOG_LEVEL}
      STEGA_EDGE_SERVICE_BROKER_USER: ${STEGA_EDGE_SERVICE_BROKER_USER}
      STEGA_EDGE_SERVICE_BROKER_PASS: ${STEGA_EDGE_SERVICE_BROKER_PASS}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'curl http://127.0.0.1:5000/api/health'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "127.0.0.1:20000:5000"
