[project]
authors = [{ name = "Eric Simpson", email = "eric.gr.simpson@gmail.com" }]
name = "stega_market_data"
requires-python = ">=3.12"
version = "0.1.0"
description = "Market data microservice for stega application"
dependencies = [
    "stega_core",
    "stega_config",
    "stega_contracts",
]

[tool.stega]
service = true

[build-system]
requires = ["uv_build>=0.7.20,<0.8.0"]
build-backend = "uv_build"

[dependency-groups]
dev = []

[tool.uv.sources]
stega_core = { workspace = true }
stega_config = { workspace = true }
stega_contracts = { workspace = true }
